#!/usr/bin/env node
// Renders every generated content page into public/.
//
// Run with `npm run build:content`. Idempotent — safe to re-run; it overwrites the
// files it owns and touches nothing else. Every file it writes carries a generated
// banner comment naming this script, so nobody hand-edits a page that will be
// regenerated.
//
// Review rail: case studies marked `reviewNeeded: true` ARE written, but every run
// prints them as an explicit review list. Their solution descriptions were inferred
// from client needs rather than verified against what was deployed, and each also
// needs the client's permission to be named publicly. Clear the flag per entry in
// content/case-studies.js as each one is checked.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  page, hero, prose, cardGrid, faq, cta, keyFacts, table, relatedLinks, picture, esc, abs,
} from './seo/render.mjs';
import { ORIGIN, ORG } from '../content/site.js';
import { PRODUCTS, flagship, agents, apps, pageProducts } from '../content/products.js';
import { SERVICES } from '../content/services.js';
import { INDUSTRIES } from '../content/industries.js';
import { COMPARISONS } from '../content/comparisons.js';
import { CASE_STUDIES } from '../content/case-studies.js';
import { GUIDES, allGuidePages } from '../content/guides.js';
import { BOOKS } from '../content/books.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'public');

const BANNER = '<!-- Generated by scripts/build-content.mjs — do not edit by hand. Edit content/*.js instead. -->\n';

const written = [];
const needsReview = [];

function write(urlPath, html) {
  const file = join(OUT, urlPath.replace(/^\//, ''), 'index.html');
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, BANNER + html);
  written.push(urlPath);
}

const HOME = { label: 'Home', href: '/' };

/* ------------------------------------------------------------ prose helpers */

// Renders a content section object into prose HTML. `p` and `p2` are paragraph
// arrays, `ul`/`ol` are lists, `note` is a callout, `links` becomes a link list.
function section(s) {
  const out = [];
  if (s.h) out.push(`<h2>${esc(s.h)}</h2>`);
  for (const paragraph of s.p || []) out.push(`<p>${paragraph}</p>`);
  if (s.ul) out.push(`<ul>${s.ul.map(li => `<li>${li}</li>`).join('')}</ul>`);
  if (s.ol) out.push(`<ol>${s.ol.map(li => `<li>${li}</li>`).join('')}</ol>`);
  for (const paragraph of s.p2 || []) out.push(`<p>${paragraph}</p>`);
  if (s.note) out.push(`<p class="note"><strong>Worth saying:</strong> ${s.note}</p>`);
  if (s.links) {
    out.push(`<ul>${s.links.map(l => `<li><a href="${l.href}">${esc(l.label)}</a>${l.note ? ` — ${esc(l.note)}` : ''}</li>`).join('')}</ul>`);
  }
  return out.join('\n');
}

const sectionsToProse = list => prose(list.map(section));

/* ----------------------------------------------------------------- products */

function productGraph(product) {
  const url = `${ORIGIN}/products/${product.slug}/`;
  // SoftwareApplication, never Product. Google's Product rich result requires one of
  // offers / review / aggregateRating, and these pages deliberately show no price —
  // prices live in server/checkout.js and appear only on /starter-pack/. A Product
  // node here would be invalid by construction; Search Console flagged exactly this
  // on the pre-existing /products/ markup (19 invalid items, "Either offers, review,
  // or aggregateRating should be specified"). SoftwareApplication is accurate for
  // every one of these and carries no offers requirement.
  return [
    {
      '@type': 'SoftwareApplication',
      '@id': `${url}#product`,
      name: product.name,
      url,
      description: product.description,
      ...(product.image ? { image: abs(product.image) } : {}),
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      publisher: { '@id': `${ORIGIN}/#organization` },
    },
  ];
}

function buildProduct(product) {
  const path = `/products/${product.slug}/`;
  const trail = [HOME, { label: 'Products', href: '/products/' }, { label: product.name, href: path }];
  const body = [
    hero({
      eyebrow: product.tag,
      h1: product.name,
      lede: esc(product.lede),
      ctas: [
        { label: `Ask about ${product.name}`, href: `/contact/?product=${encodeURIComponent(product.name)}` },
        { label: 'Book a call', href: '/booking/' },
      ],
    }),
    product.facts.length ? keyFacts(product.facts) : '',
    product.image
      ? `<section class="band"><div class="shell"><figure>${picture({
          src: product.image,
          alt: `${product.name} product screenshot`,
          width: 1200,
          height: 750,
        })}<figcaption>${esc(product.name)}</figcaption></figure></div></section>`
      : '',
    sectionsToProse(product.sections),
    product.faq.length ? faq(product.faq) : '',
    product.related.length ? relatedLinks({ links: product.related }) : '',
    cta({
      heading: `Talk to us about ${product.name}`,
      body: 'A short call, and a straight answer about whether this fits your business.',
      primary: { label: 'Book a call', href: '/booking/' },
      secondary: { label: 'Send a message', href: `/contact/?product=${encodeURIComponent(product.name)}` },
    }),
  ].filter(Boolean).join('\n');

  write(path, page({
    title: product.title,
    description: product.description,
    canonical: path,
    trail,
    extraGraph: productGraph(product),
    image: product.image,
    imageAlt: `${product.name} — Felican AI`,
    body,
    activeNav: '/products/',
  }));
}

function buildProductsHub() {
  const path = '/products/hub/';
  // The existing /products/ page stays as-is; this is an additional, fully static
  // index that a text-only crawler can read. It is linked from the nav so it is not
  // orphaned, and it carries the ItemList schema.
  const toCard = p => ({
    tag: p.tag,
    title: p.name,
    body: esc(p.lede || p.description),
    href: `/products/${p.slug}/`,
  });
  const body = [
    hero({
      eyebrow: 'Products',
      h1: 'Every product, one page each',
      lede: 'Nineteen products, each with its own page explaining what it does, who it is for, how it deploys and what drives the cost.',
      ctas: [{ label: 'Book a call', href: '/booking/' }, { label: 'Starter Pack', href: '/starter-pack/' }],
    }),
    cardGrid({
      eyebrow: 'Flagship',
      heading: 'The core products',
      intro: 'The ones most businesses start with.',
      cards: flagship().map(toCard),
    }),
    cardGrid({
      eyebrow: 'Agents that do real work',
      heading: 'Specialists, not chatbots',
      intro: 'Each one is pointed at a single job and produces output you can act on.',
      cards: agents().map(toCard),
    }),
    cardGrid({
      eyebrow: 'Also from the factory',
      heading: 'The rest of the bench',
      cards: apps().map(toCard),
      cols: 4,
    }),
    cta({
      heading: 'Need something none of these do?',
      body: 'That is most of our work. We build custom AI systems around how your business already runs.',
      primary: { label: 'See our services', href: '/services/' },
      secondary: { label: 'Start a conversation', href: '/contact/' },
    }),
  ].join('\n');

  write(path, page({
    title: 'All products — Felican AI',
    description: 'Every Felican AI product with its own page: Private AI, Chat AI Assistant, Voice AI, Felican IDP, CrossCheck AI, Relay and the rest of the bench.',
    canonical: path,
    trail: [HOME, { label: 'Products', href: '/products/' }, { label: 'All products', href: path }],
    extraGraph: [{
      '@type': 'ItemList',
      '@id': `${ORIGIN}${path}#list`,
      itemListElement: pageProducts().map((p, i) => ({
        '@type': 'ListItem', position: i + 1, name: p.name, url: `${ORIGIN}/products/${p.slug}/`,
      })),
    }],
    body,
    activeNav: '/products/',
  }));
}

/* ----------------------------------------------------------------- services */

function buildService(service) {
  const path = `/services/${service.slug}/`;
  const trail = [HOME, { label: 'Services', href: '/services/' }, { label: service.name, href: path }];
  const body = [
    hero({
      eyebrow: service.tag,
      h1: service.name,
      lede: esc(service.lede),
      ctas: [{ label: 'Book a call', href: '/booking/' }, { label: 'Send a message', href: '/contact/' }],
    }),
    prose([
      `<h2>What is in scope</h2><ul>${service.scope.map(s => `<li>${s}</li>`).join('')}</ul>`,
      `<h2>How the engagement runs</h2><ol>${service.engagement.map(s => `<li>${s}</li>`).join('')}</ol>`,
      `<h2>What determines the price</h2>${service.pricing.map(p => `<p>${p}</p>`).join('')}`,
      `<h2>When this is the wrong service</h2><p>Stated plainly, because an engagement that should not have happened costs us more than it costs you.</p><ul>${service.notFor.map(s => `<li>${s}</li>`).join('')}</ul>`,
    ]),
    service.related.length ? relatedLinks({ links: service.related }) : '',
    cta({
      heading: 'Bring us the process that keeps breaking',
      body: 'A short call is usually enough to tell you whether this is the right service.',
      primary: { label: 'Book a call', href: '/booking/' },
      secondary: { label: 'All services', href: '/services/engagements/' },
    }),
  ].filter(Boolean).join('\n');

  write(path, page({
    title: service.title,
    description: service.description,
    canonical: path,
    trail,
    extraGraph: [{
      '@type': 'Service',
      '@id': `${ORIGIN}${path}#service`,
      name: service.name,
      url: `${ORIGIN}${path}`,
      description: service.description,
      provider: { '@id': `${ORIGIN}/#organization` },
      areaServed: ORG.areaServed.map(name => ({ '@type': 'AdministrativeArea', name })),
      serviceType: service.name,
    }],
    body,
    activeNav: '/services/',
  }));
}

function buildServicesHub() {
  const path = '/services/engagements/';
  const body = [
    hero({
      eyebrow: 'Services',
      h1: 'Eleven ways we put AI to work',
      lede: 'Each service has its own page covering scope, how the engagement runs, what drives the price, and when you should not buy it.',
      ctas: [{ label: 'Book a call', href: '/booking/' }],
    }),
    cardGrid({
      heading: 'Every service',
      cards: SERVICES.map(s => ({ tag: s.tag, title: s.name, body: esc(s.lede), href: `/services/${s.slug}/` })),
    }),
    cta({
      heading: 'Not sure which one you need?',
      body: 'That is what the first call is for, and it often ends with us recommending less than you expected.',
      primary: { label: 'Book a call', href: '/booking/' },
      secondary: { label: 'Send a message', href: '/contact/' },
    }),
  ].join('\n');

  write(path, page({
    title: 'All services — Felican AI',
    description: 'Every Felican AI service: private AI systems, AI agents, business automation, integrations, consulting, auditing, cost reduction and training.',
    canonical: path,
    trail: [HOME, { label: 'Services', href: '/services/' }, { label: 'All engagements', href: path }],
    extraGraph: [{
      '@type': 'ItemList',
      '@id': `${ORIGIN}${path}#list`,
      itemListElement: SERVICES.map((s, i) => ({
        '@type': 'ListItem', position: i + 1, name: s.name, url: `${ORIGIN}/services/${s.slug}/`,
      })),
    }],
    body,
    activeNav: '/services/',
  }));
}

/* --------------------------------------------------------------- industries */

function buildIndustry(industry) {
  const path = `/industries/${industry.slug}/`;
  const trail = [HOME, { label: 'Industries', href: '/industries/' }, { label: industry.name, href: path }];
  const body = [
    hero({
      eyebrow: `AI for ${industry.longName.toLowerCase()}`,
      h1: `AI for ${industry.longName}`,
      lede: esc(industry.lede),
      ctas: [{ label: 'Book a call', href: '/booking/' }, { label: 'Send a message', href: '/contact/' }],
    }),
    prose([
      '<h2>The problem, specifically</h2>',
      ...industry.theProblem.map(p => `<p>${p}</p>`),
      '<h2>What we deploy</h2>',
      ...industry.whatWeDeploy.map(
        d => `<h3><a href="${d.href}">${esc(d.product)}</a></h3><p>${d.detail}</p>`,
      ),
      '<h2>What makes this different in your trade</h2>',
      ...industry.specifics.map(s => `<h3>${esc(s.h)}</h3><p>${s.p}</p>`),
    ]),
    faq(industry.faq),
    relatedLinks({
      heading: 'Related',
      links: [
        { href: '/guides/ai-receptionist/', label: 'The AI receptionist guide', note: 'How these systems work, in full' },
        { href: '/case-studies/', label: 'Client work', note: 'Real deployments' },
        { href: '/industries/', label: 'All industries', note: 'Every trade we build for' },
      ],
    }),
    cta({
      heading: `Talk to someone who knows ${industry.name.toLowerCase()}`,
      body: 'A short call, and an honest answer about whether this is worth doing for your business.',
      primary: { label: 'Book a call', href: '/booking/' },
      secondary: { label: 'Send a message', href: '/contact/' },
    }),
  ].join('\n');

  write(path, page({
    title: industry.title,
    description: industry.description,
    canonical: path,
    trail,
    extraGraph: [{
      '@type': 'Service',
      '@id': `${ORIGIN}${path}#service`,
      name: `AI for ${industry.longName}`,
      url: `${ORIGIN}${path}`,
      description: industry.description,
      provider: { '@id': `${ORIGIN}/#organization` },
      audience: { '@type': 'BusinessAudience', name: industry.longName },
      areaServed: ORG.areaServed.map(name => ({ '@type': 'AdministrativeArea', name })),
    }],
    body,
    activeNav: '/industries/',
  }));
}

function buildIndustriesHub() {
  const path = '/industries/';
  const body = [
    hero({
      eyebrow: 'Industries',
      h1: 'The trades and practices we build for',
      lede: 'The method does not change between industries. The failure we are designing around does, which is why each of these has its own page rather than a paragraph.',
      ctas: [{ label: 'Book a call', href: '/booking/' }],
    }),
    cardGrid({
      heading: 'Pick your trade',
      cards: INDUSTRIES.map(i => ({ tag: i.name, title: i.longName, body: esc(i.lede), href: `/industries/${i.slug}/` })),
    }),
    cta({
      heading: 'Not listed?',
      body: 'Most of our work is outside these eight. The shape of the problem is usually familiar even when the trade is not.',
      primary: { label: 'Start a conversation', href: '/contact/' },
      secondary: { label: 'See our services', href: '/services/engagements/' },
    }),
  ].join('\n');

  write(path, page({
    title: 'Industries we serve — AI for trades, practices and manufacturers | Felican AI',
    description: 'AI built for specific industries: HVAC, plumbing, electrical, medical and dental, legal, pool and outdoor services, and manufacturing.',
    canonical: path,
    trail: [HOME, { label: 'Industries', href: path }],
    extraGraph: [{
      '@type': 'ItemList',
      '@id': `${ORIGIN}${path}#list`,
      itemListElement: INDUSTRIES.map((i, n) => ({
        '@type': 'ListItem', position: n + 1, name: `AI for ${i.longName}`, url: `${ORIGIN}/industries/${i.slug}/`,
      })),
    }],
    body,
    activeNav: '/industries/',
  }));
}

/* -------------------------------------------------------------- comparisons */

function buildComparison(cmp) {
  const path = `/compare/${cmp.slug}/`;
  const trail = [HOME, { label: 'Comparisons', href: '/compare/' }, { label: cmp.h1, href: path }];
  const body = [
    hero({ eyebrow: 'Comparison', h1: cmp.h1, lede: esc(cmp.lede) }),
    `<section class="band"><div class="shell"><p class="eyebrow">The short answer</p><h2>Our verdict, including where we lose</h2><p class="intro">${esc(cmp.verdict)}</p></div></section>`,
    cmp.table
      ? `<section class="band band-alt"><div class="shell"><p class="eyebrow">Side by side</p><h2>${esc(cmp.table.caption)}</h2>${table(cmp.table)}</div></section>`
      : '',
    sectionsToProse(cmp.sections),
    faq(cmp.faq),
    relatedLinks({ links: cmp.related }),
    cta({
      heading: 'Want this run against your numbers?',
      body: 'Bring your actual volumes and invoices. If the other option wins, we will tell you.',
      primary: { label: 'Book a call', href: '/booking/' },
      secondary: { label: 'Send a message', href: '/contact/' },
    }),
  ].filter(Boolean).join('\n');

  write(path, page({
    title: cmp.title,
    description: cmp.description,
    canonical: path,
    trail,
    ogType: 'article',
    extraGraph: [{
      '@type': 'Article',
      '@id': `${ORIGIN}${path}#article`,
      headline: cmp.h1,
      description: cmp.description,
      url: `${ORIGIN}${path}`,
      author: { '@id': `${ORIGIN}/#founder` },
      publisher: { '@id': `${ORIGIN}/#organization` },
      inLanguage: 'en-US',
      isPartOf: { '@id': `${ORIGIN}/#website` },
    }],
    body,
    activeNav: '/compare/',
  }));
}

function buildComparisonsHub() {
  const path = '/compare/';
  const body = [
    hero({
      eyebrow: 'Comparisons',
      h1: 'Comparisons, including the ones we lose',
      lede: 'Every page here concedes at least one real point to the alternative and says plainly when you should not buy from us. A comparison that never gives ground is an advert.',
    }),
    cardGrid({
      heading: 'Pick a decision',
      cards: COMPARISONS.map(c => ({ title: c.h1, body: esc(c.verdict), href: `/compare/${c.slug}/` })),
      cols: 2,
    }),
  ].join('\n');
  write(path, page({
    title: 'AI comparisons — Felican AI',
    description: 'Honest comparisons for business AI decisions: private AI vs ChatGPT Enterprise, AI receptionist vs answering service, document processing vs manual entry, self-hosted vs cloud for regulated work.',
    canonical: path,
    trail: [HOME, { label: 'Comparisons', href: path }],
    body,
    activeNav: '/compare/',
  }));
}

/* ------------------------------------------------------------- case studies */

function buildCaseStudy(study) {
  const path = `/case-studies/${study.slug}/`;
  if (study.reviewNeeded) {
    needsReview.push(`${path}  ${study.client} — verify deployed: ${study.deployed.join(', ')}`);
  }
  const trail = [HOME, { label: 'Client work', href: '/case-studies/' }, { label: study.client, href: path }];
  const body = [
    hero({
      eyebrow: study.industry,
      h1: study.client,
      lede: esc(study.summary),
      ctas: [{ label: 'Book a call', href: '/booking/' }],
    }),
    keyFacts([
      { k: 'Industry', v: esc(study.industry) },
      { k: 'Location', v: esc(study.location) },
      { k: 'Deployed', v: study.deployed.map(esc).join(', ') },
      ...(study.clientUrl ? [{ k: 'Client', v: `<a href="${esc(study.clientUrl)}" rel="nofollow noopener">${esc(study.client)}</a>` }] : []),
    ]),
    prose([
      `<h2>About ${esc(study.client)}</h2><p>${esc(study.about)}</p>`,
      '<h2>The situation</h2>',
      ...study.situation.map(p => `<p>${p}</p>`),
      '<h2>What we built</h2>',
      ...study.built.map(p => `<p>${p}</p>`),
      `<h2>Why this shape</h2><p>${study.why}</p>`,
      ...(study.note ? [`<p class="note"><strong>Worth saying:</strong> ${study.note}</p>`] : []),
    ]),
    relatedLinks({ heading: 'What was deployed', links: study.products.map(p => ({ ...p, note: '' })) }),
    cta({
      heading: 'Something similar in your business?',
      body: 'A short call, and a straight answer about whether the same approach fits.',
      primary: { label: 'Book a call', href: '/booking/' },
      secondary: { label: 'Send a message', href: '/contact/' },
    }),
  ].join('\n');

  write(path, page({
    title: study.title,
    description: study.description,
    canonical: path,
    trail,
    ogType: 'article',
    extraGraph: [{
      '@type': 'Article',
      '@id': `${ORIGIN}${path}#article`,
      headline: `${study.client} — ${study.industry}`,
      description: study.description,
      url: `${ORIGIN}${path}`,
      author: { '@id': `${ORIGIN}/#founder` },
      publisher: { '@id': `${ORIGIN}/#organization` },
      about: { '@type': 'Organization', name: study.client },
      inLanguage: 'en-US',
    }],
    body,
    activeNav: '/case-studies/',
  }));
}

function buildCaseStudiesHub() {
  const path = '/case-studies/';
  const visible = CASE_STUDIES;
  const body = [
    hero({
      eyebrow: 'Client work',
      h1: 'What we have actually built',
      lede: visible.length
        ? 'Real deployments, described by what was built rather than by invented metrics. Where a measured result is not available, this says so.'
        : 'Client pages are being prepared and are not published yet.',
      ctas: [{ label: 'Book a call', href: '/booking/' }],
    }),
    visible.length
      ? cardGrid({
          heading: 'Deployments',
          cards: visible.map(s => ({
            tag: s.industry, title: s.client, body: esc(s.summary),
            meta: esc(s.deployed.join(' · ')), href: `/case-studies/${s.slug}/`,
          })),
        })
      : `<section class="band"><div class="shell"><p class="intro">These pages are drafted and awaiting client sign-off on naming and on the deployment detail. They will publish once confirmed.</p></div></section>`,
    cta({
      heading: 'Want to talk to one of them?',
      body: 'We will put you in touch with a client in a comparable business where they have agreed to it.',
      primary: { label: 'Book a call', href: '/booking/' },
      secondary: { label: 'Send a message', href: '/contact/' },
    }),
  ].join('\n');

  write(path, page({
    title: 'Client work — AI deployments by Felican AI',
    description: 'Real AI deployments by Felican AI across manufacturing, healthcare, field service, distribution, legal and recreation.',
    canonical: path,
    trail: [HOME, { label: 'Client work', href: path }],
    // Deliberately noindex while every entry is unconfirmed: an index page listing
    // nothing is a thin page, and thin pages on a small site do measurable harm.
    robots: visible.length ? undefined : 'noindex,follow',
    body,
    activeNav: '/case-studies/',
  }));
}

/* -------------------------------------------------------------------- guides */

function articleGraph(path, headline, description, datePublished) {
  return [{
    '@type': 'Article',
    '@id': `${ORIGIN}${path}#article`,
    headline,
    description,
    url: `${ORIGIN}${path}`,
    author: { '@id': `${ORIGIN}/#founder` },
    publisher: { '@id': `${ORIGIN}/#organization` },
    inLanguage: 'en-US',
    isPartOf: { '@id': `${ORIGIN}/#website` },
    ...(datePublished ? { datePublished, dateModified: datePublished } : {}),
  }];
}

function buildGuidePillar(guide) {
  const path = `/guides/${guide.slug}/`;
  const trail = [HOME, { label: 'Guides', href: '/guides/' }, { label: guide.pillar, href: path }];
  const body = [
    hero({ eyebrow: `Guide · ${guide.pillar}`, h1: guide.h1, lede: esc(guide.lede) }),
    sectionsToProse(guide.sections),
    faq(guide.faq),
    (guide.children || []).length
      ? relatedLinks({
          heading: 'In this guide',
          links: guide.children.map(c => ({
            href: `/guides/${guide.slug}/${c.slug}/`, label: c.h1, note: c.lede.slice(0, 110),
          })),
        })
      : '',
    cta({
      heading: 'Want this applied to your business?',
      body: 'A short call, and an honest read on whether it is worth doing.',
      primary: { label: 'Book a call', href: '/booking/' },
      secondary: { label: 'Send a message', href: '/contact/' },
    }),
  ].filter(Boolean).join('\n');

  write(path, page({
    title: guide.title,
    description: guide.description,
    canonical: path,
    trail,
    ogType: 'article',
    extraGraph: articleGraph(path, guide.h1, guide.description, guide.updated),
    body,
    activeNav: '/guides/',
  }));
}

function buildGuideChild(guide, child) {
  const path = `/guides/${guide.slug}/${child.slug}/`;
  const trail = [
    HOME,
    { label: 'Guides', href: '/guides/' },
    { label: guide.pillar, href: `/guides/${guide.slug}/` },
    { label: child.h1, href: path },
  ];
  const body = [
    hero({ eyebrow: `${guide.pillar} guide`, h1: child.h1, lede: esc(child.lede) }),
    sectionsToProse(child.sections),
    faq(child.faq),
    relatedLinks({
      heading: 'Back to the guide',
      links: [
        { href: `/guides/${guide.slug}/`, label: guide.h1, note: `The full ${guide.pillar.toLowerCase()} guide` },
        ...guide.children.filter(c => c.slug !== child.slug).map(c => ({
          href: `/guides/${guide.slug}/${c.slug}/`, label: c.h1, note: '',
        })),
      ],
    }),
    cta({
      heading: 'Still have the question?',
      body: 'Ask us directly. We answer these on calls all day.',
      primary: { label: 'Book a call', href: '/booking/' },
      secondary: { label: 'Send a message', href: '/contact/' },
    }),
  ].join('\n');

  write(path, page({
    title: child.title,
    description: child.description,
    canonical: path,
    trail,
    ogType: 'article',
    extraGraph: articleGraph(path, child.h1, child.description, guide.updated),
    body,
    activeNav: '/guides/',
  }));
}

function buildGuidesHub() {
  const path = '/guides/';
  const body = [
    hero({
      eyebrow: 'Guides',
      h1: 'Guides worth the reading time',
      lede: 'Three subjects we can write about from deployment experience rather than from research. Each one includes the parts that argue against buying from us.',
    }),
    ...GUIDES.map(g => cardGrid({
      eyebrow: g.pillar,
      heading: g.h1,
      intro: esc(g.lede),
      cards: [
        { title: `Read the ${g.pillar.toLowerCase()} guide`, body: esc(g.description), href: `/guides/${g.slug}/`, tag: 'Pillar' },
        ...(g.children || []).map(c => ({ title: c.h1, body: esc(c.lede), href: `/guides/${g.slug}/${c.slug}/` })),
      ],
    })),
    cta({
      heading: 'Rather just ask?',
      body: 'Most of what is written here started as a question on a call.',
      primary: { label: 'Book a call', href: '/booking/' },
      secondary: { label: 'Send a message', href: '/contact/' },
    }),
  ].join('\n');

  write(path, page({
    title: 'AI guides for business — private AI, receptionists, governance | Felican AI',
    description: 'Practical AI guides from Felican AI: self-hosted private AI, AI receptionists, and AI governance — written from deployment experience.',
    canonical: path,
    trail: [HOME, { label: 'Guides', href: path }],
    extraGraph: [{
      '@type': 'ItemList',
      '@id': `${ORIGIN}${path}#list`,
      itemListElement: allGuidePages().map((g, i) => ({
        '@type': 'ListItem', position: i + 1, name: g.h1, url: `${ORIGIN}${g.path}`,
      })),
    }],
    body,
    activeNav: '/guides/',
  }));
}

/* --------------------------------------------------------------------- books */

function buildBook(book) {
  const path = `/books/${book.slug}/`;
  const trail = [HOME, { label: 'Books', href: '/books/' }, { label: book.name, href: path }];
  const body = [
    hero({
      eyebrow: `Book by ${ORG.founder.name}`,
      h1: book.name,
      lede: esc(book.tagline),
      ctas: book.buyUrl
        ? [{ label: 'Get the book', href: book.buyUrl }, { label: 'All books', href: '/books/' }]
        : [{ label: 'All books', href: '/books/' }, { label: 'Ask about it', href: '/contact/' }],
    }),
    `<section class="band"><div class="shell"><figure>${picture({
      src: book.cover,
      alt: `${book.name} cover`,
      width: 600,
      height: 900,
      style: 'max-width:320px',
    })}</figure></div></section>`,
    prose([
      '<h2>What it is about</h2>',
      ...book.about.map(p => `<p>${esc(p)}</p>`),
      `<h2>Read it if</h2><ul>${book.forYouIf.map(s => `<li>${esc(s)}</li>`).join('')}</ul>`,
      `<h2>About the author</h2><p>${esc(ORG.founder.name)} is ${esc(ORG.founder.jobTitle.toLowerCase())} at Felican AI, where he builds and deploys the AI systems these books describe. <a href="/about/">More about the team</a>.</p>`,
    ]),
    relatedLinks({ links: book.related }),
  ].join('\n');

  write(path, page({
    title: book.title,
    description: book.description,
    canonical: path,
    trail,
    ogType: 'book',
    image: book.cover,
    imageAlt: `${book.name} cover`,
    extraGraph: [{
      '@type': 'Book',
      '@id': `${ORIGIN}${path}#book`,
      name: book.name,
      url: `${ORIGIN}${path}`,
      description: book.description,
      image: abs(book.cover),
      author: { '@id': `${ORIGIN}/#founder` },
      inLanguage: 'en',
    }],
    body,
    activeNav: '/books/',
  }));
}

function buildBooksHub() {
  const path = '/books/library/';
  const body = [
    hero({
      eyebrow: 'Books',
      h1: `Four books by ${ORG.founder.name}`,
      lede: 'Each one has its own page with what it covers and who it is for.',
    }),
    cardGrid({
      heading: 'The library',
      cards: BOOKS.map(b => ({ title: b.name, body: esc(b.tagline), href: `/books/${b.slug}/` })),
      cols: 4,
    }),
  ].join('\n');
  write(path, page({
    title: `Books by ${ORG.founder.name} — Felican AI`,
    description: `All four books by ${ORG.founder.name}: The BIG AI Book, Stop Being Nice to AI, Don't Be Replaced, and Big Ballas Guide.`,
    canonical: path,
    trail: [HOME, { label: 'Books', href: '/books/' }, { label: 'The library', href: path }],
    extraGraph: [{
      '@type': 'ItemList',
      '@id': `${ORIGIN}${path}#list`,
      itemListElement: BOOKS.map((b, i) => ({
        '@type': 'ListItem', position: i + 1, name: b.name, url: `${ORIGIN}/books/${b.slug}/`,
      })),
    }],
    body,
    activeNav: '/books/',
  }));
}

/* ------------------------------------------------------------------ location */

function buildLocation() {
  const path = '/locations/palm-beach-county/';
  const body = [
    hero({
      eyebrow: 'South Florida',
      h1: 'AI consultants in Palm Beach County',
      lede: 'We are based in Palm Beach County and most of our clients are within an hour of us — which means someone can be in your building rather than on a call.',
      ctas: [{ label: 'Book a call', href: '/booking/' }, { label: `Call ${ORG.telephoneDisplay}`, href: 'tel:+15612350799' }],
    }),
    prose([
      '<h2>Why local matters for this work</h2>',
      '<p>Most AI consulting happens over video, and for a lot of it that is fine. For two parts of it, it is not.</p>',
      '<p>The first is the assessment. Watching how work actually happens — the paper on the desk, the three screens, the call that interrupts everything — tells you things nobody reports in an interview. The documented process and the real process are different in every business we have worked in, and the gap is where the value usually is.</p>',
      '<p>The second is a private deployment. When the system runs on hardware in your building, somebody eventually needs to be in the room with it.</p>',
      '<h2>Where we work</h2>',
      '<p>Palm Beach County, Broward and Miami-Dade for on-site work — Wellington, West Palm Beach, Boca Raton, Delray Beach, Jupiter, Deerfield Beach, Coral Springs, Fort Lauderdale and Miami. Our client list already spans Miami-Dade to Palm Beach, and we work with businesses nationwide remotely.</p>',
      '<h2>South Florida businesses we already build for</h2>',
      '<p>Manufacturing and industrial hardware, pool and outdoor services, automotive customisation, product development, document destruction, swim schools and healthcare — the specifics are on the <a href="/case-studies/">client work</a> and <a href="/industries/">industries</a> pages.</p>',
      '<h2>Getting in touch</h2>',
      `<p>Call <a href="tel:+15612350799">${esc(ORG.telephoneDisplay)}</a>, email <a href="mailto:${ORG.email}">${ORG.email}</a>, or <a href="/booking/">book a time</a>. We serve clients at their sites rather than from a storefront, so there is nowhere to walk into — the first conversation is a call or a visit to you.</p>`,
    ]),
    cta({
      heading: 'Based in South Florida?',
      body: 'We can come to you. That is usually a better first meeting than a video call.',
      primary: { label: 'Book a call', href: '/booking/' },
      secondary: { label: 'Send a message', href: '/contact/' },
    }),
  ].join('\n');

  write(path, page({
    title: 'AI consultants in Palm Beach County, Florida | Felican AI',
    description: `AI consultants serving Palm Beach County, Broward and Miami-Dade. Private AI, AI receptionists, automation and training. Call ${ORG.telephoneDisplay}.`,
    canonical: path,
    trail: [HOME, { label: 'Palm Beach County', href: path }],
    extraGraph: [{
      '@type': 'ProfessionalService',
      '@id': `${ORIGIN}${path}#localbusiness`,
      name: ORG.name,
      url: `${ORIGIN}${path}`,
      telephone: ORG.telephone,
      email: ORG.email,
      image: ORG.image,
      parentOrganization: { '@id': `${ORIGIN}/#organization` },
      // Service-area business: no street address published, by the owner's choice.
      address: { '@type': 'PostalAddress', addressRegion: 'FL', addressCountry: 'US' },
      areaServed: [
        'Palm Beach County, Florida', 'Broward County, Florida', 'Miami-Dade County, Florida',
      ].map(name => ({ '@type': 'AdministrativeArea', name })),
      priceRange: '$$',
    }],
    body,
  }));
}

/* ------------------------------------------------------------------ sitemap */

function buildSitemap() {
  // Generated rather than hand-maintained: the previous static file already omitted
  // /starter-pack/, and hand-editing 70 entries guarantees drift. changefreq and
  // priority are deliberately omitted — Google ignores both.
  const existing = [
    '/', '/products/', '/services/', '/education/', '/books/', '/about/',
    '/contact/', '/booking/', '/starter-pack/', '/starter-pack/ai-engines/',
    '/privacy/', '/terms/',
  ];
  const today = new Date().toISOString().slice(0, 10);
  const urls = [...new Set([...existing, ...written])].sort();
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `  <url><loc>${ORIGIN}${u}</loc><lastmod>${today}</lastmod></url>`).join('\n')}
</urlset>
`;
  writeFileSync(join(OUT, 'sitemap.xml'), xml);
  return urls.length;
}

/* --------------------------------------------------------------------- main */

buildProductsHub();
for (const product of pageProducts()) buildProduct(product);

buildServicesHub();
for (const service of SERVICES) buildService(service);

buildIndustriesHub();
for (const industry of INDUSTRIES) buildIndustry(industry);

buildComparisonsHub();
for (const cmp of COMPARISONS) buildComparison(cmp);

buildCaseStudiesHub();
for (const study of CASE_STUDIES) buildCaseStudy(study);

buildGuidesHub();
for (const guide of GUIDES) {
  buildGuidePillar(guide);
  for (const child of guide.children || []) buildGuideChild(guide, child);
}

buildBooksHub();
for (const book of BOOKS) buildBook(book);

buildLocation();

const sitemapCount = buildSitemap();

console.log(`\nGenerated ${written.length} pages into public/`);
console.log(`Sitemap: ${sitemapCount} URLs\n`);
if (needsReview.length) {
  console.log(`REVIEW BEFORE DEPLOY — ${needsReview.length} client page(s) need a factual check`);
  console.log('Each needs (a) the deployment detail verified against what was actually');
  console.log('built, and (b) the client\'s permission to be named publicly.\n');
  for (const s of needsReview) console.log(`  - ${s}`);
  console.log('\nClear `reviewNeeded` in content/case-studies.js as each is confirmed.\n');
}
