// Guards the generated content pages. With ~74 of them, a defect in the renderer is
// a defect on every page at once, so these assertions run over all of them.
//
// The checks are the ones that actually cost traffic when they break: a missing or
// wrong canonical, a duplicated title, an unrendered {{ template }} braces leak, an
// internal link to a URL that does not exist, a broken JSON-LD graph, or an <img>
// with no dimensions.

import { readFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

const ROOT = resolve(process.cwd());
const PUBLIC = join(ROOT, 'public');
const GENERATED = '<!-- Generated by scripts/build-content.mjs';

function walk(dir, out = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else if (entry.name === 'index.html') out.push(full);
  }
  return out;
}

const pages = walk(PUBLIC)
  .filter(file => readFileSync(file, 'utf8').startsWith(GENERATED))
  .map(file => {
    const html = readFileSync(file, 'utf8');
    const urlPath = `${file.slice(PUBLIC.length).replace(/index\.html$/, '')}`;
    return { file, urlPath, html };
  });

const first = (html, re) => (html.match(re) || [])[1] || '';

describe('generated content pages', () => {
  it('there are pages to check', () => {
    // Fails loudly if the build was never run, rather than silently passing on zero.
    expect(pages.length).toBeGreaterThan(50);
  });

  it('every page has a canonical matching its own path', () => {
    const wrong = pages
      .map(p => ({ path: p.urlPath, canonical: first(p.html, /<link rel="canonical" href="([^"]+)"/) }))
      .filter(p => p.canonical !== `https://felican.ai${p.path}`);
    expect(wrong).toEqual([]);
  });

  it('every page has exactly one h1', () => {
    const bad = pages
      .map(p => ({ path: p.urlPath, count: (p.html.match(/<h1\b/g) || []).length }))
      .filter(p => p.count !== 1);
    expect(bad).toEqual([]);
  });

  it('every page has a non-empty title and meta description', () => {
    const bad = pages
      .filter(p => {
        const title = first(p.html, /<title>([^<]*)<\/title>/);
        const description = first(p.html, /<meta name="description" content="([^"]*)"/);
        return !title.trim() || description.trim().length < 50;
      })
      .map(p => p.urlPath);
    expect(bad).toEqual([]);
  });

  it('titles are unique across the generated set', () => {
    const seen = new Map();
    for (const p of pages) {
      const title = first(p.html, /<title>([^<]*)<\/title>/);
      if (seen.has(title)) seen.get(title).push(p.urlPath);
      else seen.set(title, [p.urlPath]);
    }
    const duplicates = [...seen.entries()].filter(([, paths]) => paths.length > 1);
    expect(duplicates).toEqual([]);
  });

  it('no page leaks an unrendered template expression', () => {
    // The generated pages are plain HTML and must never contain <x-dc> templating.
    // JSON-LD legitimately contains }} where objects nest, so script blocks are
    // stripped before checking the markup.
    // <dc-import name="ChatAssistant"> is deliberate — it is the shared component
    // carrying the assistant launcher and the gold credentials bar that every other
    // page has. Nothing else may be templated: the page's own content must be static.
    const leaking = pages
      .filter(p => {
        const markup = p.html
          .replace(/<script[\s\S]*?<\/script>/g, '')
          .replace(/<dc-import name="ChatAssistant"[^>]*><\/dc-import>/g, '');
        return /\{\{|\}\}|<sc-for|<dc-import/.test(markup);
      })
      .map(p => p.urlPath);
    expect(leaking).toEqual([]);
  });

  it('every internal link resolves to a page or a file that exists', () => {
    const known = new Set(walk(PUBLIC).map(f => f.slice(PUBLIC.length).replace(/index\.html$/, '')));
    // Hand-written pages the generator links out to.
    for (const extra of ['/', '/products/', '/services/', '/education/', '/books/', '/about/',
      '/contact/', '/booking/', '/starter-pack/', '/starter-pack/ai-engines/', '/privacy/', '/terms/']) {
      known.add(extra);
    }
    const broken = [];
    for (const p of pages) {
      for (const match of p.html.matchAll(/href="(\/[^"#?]*)[^"]*"/g)) {
        const href = match[1];
        if (known.has(href)) continue;
        if (existsSync(join(PUBLIC, href.replace(/^\//, '')))) continue;
        broken.push(`${p.urlPath} -> ${href}`);
      }
    }
    expect([...new Set(broken)]).toEqual([]);
  });

  it('every page emits a parseable JSON-LD graph with the shared Organization node', () => {
    const bad = [];
    for (const p of pages) {
      const block = first(p.html, /<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
      if (!block) { bad.push(`${p.urlPath}: no JSON-LD`); continue; }
      try {
        const data = JSON.parse(block.replace(/\\u003c/g, '<'));
        const types = (data['@graph'] || []).flatMap(n => [].concat(n['@type']));
        if (!types.includes('Organization')) bad.push(`${p.urlPath}: no Organization`);
        if (!types.includes('WebSite')) bad.push(`${p.urlPath}: no WebSite`);
      } catch (error) {
        bad.push(`${p.urlPath}: invalid JSON — ${error.message}`);
      }
    }
    expect(bad).toEqual([]);
  });

  it('pages below the top level carry a BreadcrumbList', () => {
    const missing = pages
      .filter(p => p.urlPath.split('/').filter(Boolean).length >= 2)
      .filter(p => !p.html.includes('"BreadcrumbList"'))
      .map(p => p.urlPath);
    expect(missing).toEqual([]);
  });

  it('every image has explicit width and height', () => {
    const bad = [];
    for (const p of pages) {
      for (const tag of p.html.match(/<img\b[^>]*>/g) || []) {
        if (!/\bwidth=/.test(tag) || !/\bheight=/.test(tag)) bad.push(`${p.urlPath}: ${tag.slice(0, 80)}`);
      }
    }
    expect(bad).toEqual([]);
  });

  it('every raster image is offered as AVIF and WebP through <picture>', () => {
    // One URL per format. Accept-based negotiation is cache-unsafe behind Cloudflare,
    // which ignores `Vary: Accept`.
    const bad = [];
    for (const p of pages) {
      for (const match of p.html.matchAll(/<img\b[^>]*\bsrc="(\/[^"]+\.(?:png|jpe?g))"/g)) {
        const base = match[1].replace(/\.(png|jpe?g)$/i, '');
        if (!p.html.includes(`srcset="${base}.avif" type="image/avif"`)) bad.push(`${p.urlPath} -> ${match[1]} (no avif source)`);
        if (!p.html.includes(`srcset="${base}.webp" type="image/webp"`)) bad.push(`${p.urlPath} -> ${match[1]} (no webp source)`);
      }
    }
    expect(bad).toEqual([]);
  });

  it('every referenced image file exists and has a modern variant', () => {
    const missing = [];
    const unoptimised = [];
    for (const p of pages) {
      for (const match of p.html.matchAll(/<img\b[^>]*\bsrc="(\/[^"]+)"/g)) {
        const file = join(PUBLIC, match[1].replace(/^\//, ''));
        if (!existsSync(file)) { missing.push(`${p.urlPath} -> ${match[1]}`); continue; }
        if (/\.(png|jpe?g)$/i.test(match[1])) {
          const avif = file.replace(/\.(png|jpe?g)$/i, '.avif');
          if (!existsSync(avif)) unoptimised.push(match[1]);
        }
      }
    }
    expect([...new Set(missing)]).toEqual([]);
    expect([...new Set(unoptimised)]).toEqual([]);
  });

  it('no page is orphaned — each is linked from at least one other page', () => {
    const componentFiles = readdirSync(PUBLIC)
      .filter(name => name.endsWith('.dc.html'))
      .map(name => join(PUBLIC, name));
    const allHtml = [...walk(PUBLIC), ...componentFiles, join(ROOT, 'index.html')]
      .map(f => readFileSync(f, 'utf8'))
      .join('\n');
    // Links appear as a real href attribute on the generated pages, and inside the
    // <x-dc> nav and footer components as either an object literal (href: '/path/')
    // or a tuple (['Label','/path/']). Any quoted occurrence of the path counts.
    const linked = path => allHtml.includes(`href="${path}"`)
      || allHtml.includes(`'${path}'`)
      || allHtml.includes(`"${path}"`);
    const orphans = pages
      .filter(p => p.urlPath !== '/')
      .filter(p => !linked(p.urlPath))
      .map(p => p.urlPath);
    expect(orphans).toEqual([]);
  });
});

describe('sitemap', () => {
  const xml = readFileSync(join(PUBLIC, 'sitemap.xml'), 'utf8');

  it('includes every generated page', () => {
    const missing = pages.filter(p => !xml.includes(`<loc>https://felican.ai${p.urlPath}</loc>`)).map(p => p.urlPath);
    expect(missing).toEqual([]);
  });

  it('includes the commercial pages the old hand-written sitemap omitted', () => {
    for (const path of ['/starter-pack/', '/starter-pack/ai-engines/']) {
      expect(xml).toContain(`<loc>https://felican.ai${path}</loc>`);
    }
  });

  it('excludes the noindex checkout flow', () => {
    expect(xml).not.toContain('/checkout/');
    expect(xml).not.toContain('/thank-you/');
  });

  it('is valid enough to parse and has no duplicate entries', () => {
    const locs = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map(m => m[1]);
    expect(locs.length).toBeGreaterThan(70);
    expect(new Set(locs).size).toBe(locs.length);
  });
});

describe('entity identity', () => {
  const home = readFileSync(join(ROOT, 'index.html'), 'utf8');

  it('the homepage Organization graph carries an address and the founder node', () => {
    const block = first(home, /<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
    const data = JSON.parse(block.replace(/\\u003c/g, '<'));
    const org = data['@graph'].find(n => [].concat(n['@type']).includes('Organization'));
    expect(org).toBeTruthy();
    expect(org.address).toBeTruthy();
    expect(org.areaServed.length).toBeGreaterThan(0);
    const person = data['@graph'].find(n => n['@type'] === 'Person');
    expect(person).toBeTruthy();
    expect(person['@id']).toBe('https://felican.ai/#founder');
  });

  it('social profiles, when configured, are absolute https URLs', async () => {
    const { SOCIAL } = await import('../content/site.js');
    for (const profile of SOCIAL) {
      if (!profile.url) continue;
      expect(profile.url).toMatch(/^https:\/\//);
    }
  });
});

// Project copy rules from AGENTS.md. These are the owner's house rules, not SEO
// requirements, and they are easy to break by accident when writing 42,000 words.
describe('AGENTS.md copy rules', () => {
  const text = pages.map(p => p.html.replace(/<script[\s\S]*?<\/script>/g, '')).join('\n');

  it('never names a weekday', () => {
    // "Use elapsed time — 'in 2 days', 'live in 48 hours'."
    const found = pages.filter(p => /\b(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)\b/
      .test(p.html.replace(/<script[\s\S]*?<\/script>/g, ''))).map(p => p.urlPath);
    expect(found).toEqual([]);
  });

  it('never appends "Starter" to a product name', () => {
    expect(text).not.toMatch(/(Private AI|Chat AI Assistant|Voice AI|AI Receptionist)\s+Starter\b/);
  });

  it('never mentions the enterprise offering or the $25,000 product', () => {
    expect(text).not.toMatch(/\$\s?25,?000/);
    expect(text).not.toMatch(/enterprise offering/i);
  });

  it('shows a price only on the Starter Pack and product pages', () => {
    // The owner listed every product at $999 on 2026-09-11, so product pages now
    // display a price where previously none did. Everywhere else — guides,
    // comparisons, industries, client work, books — must stay price-free, or the
    // figure will drift out of sync the first time it changes.
    const priced = pages
      .filter(p => !p.urlPath.startsWith('/starter-pack/') && !p.urlPath.startsWith('/products/'))
      .filter(p => /\$\d[\d,]*/.test(p.html.replace(/<script[\s\S]*?<\/script>/g, '')))
      .map(p => p.urlPath);
    expect(priced).toEqual([]);
  });

  it('every displayed product price equals the single constant in server/checkout.js', async () => {
    const { CATALOG } = await import('../server/checkout.js');
    const expected = `$${Math.round(CATALOG['private-ai'].amount / 100).toLocaleString('en-US')}`;
    const wrong = [];
    for (const p of pages.filter(p => p.urlPath.startsWith('/products/') && p.urlPath !== '/products/hub/')) {
      const visible = p.html.replace(/<script[\s\S]*?<\/script>/g, '');
      const found = [...visible.matchAll(/\$\d[\d,]*/g)].map(m => m[0]);
      if (!found.length) wrong.push(`${p.urlPath}: no price shown`);
      for (const price of found) if (price !== expected) wrong.push(`${p.urlPath}: ${price}`);
    }
    expect(wrong).toEqual([]);
  });

  it('routes every booking CTA through the first-party /booking/ page', () => {
    // Never link a site CTA directly at Calendly or Cal.com.
    const external = pages.filter(p => /href="https:\/\/[^"]*(calendly|cal)\.com/.test(p.html)).map(p => p.urlPath);
    expect(external).toEqual([]);
  });

  it('does not emit FAQPage markup', () => {
    // Google retired FAQ rich results in May 2026 — it buys no SERP space, so the
    // question-shaped <h3> headings do the work instead.
    expect(text).not.toContain('"FAQPage"');
  });
});

// Structured-data validity across the whole site, generated and hand-written alike.
// Search Console reported 19 invalid Product items on /products/ before this pass.
describe('structured data validity', () => {
  const allPages = [join(ROOT, 'index.html'), ...walk(PUBLIC)];

  const blocksIn = file => {
    const html = readFileSync(file, 'utf8');
    return [...html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)]
      .map(m => ({ file, raw: m[1] }));
  };

  const nodes = [];
  const parseErrors = [];
  for (const file of allPages) {
    for (const { raw } of blocksIn(file)) {
      try {
        const data = JSON.parse(raw.replace(/\\u003c/g, '<'));
        const visit = node => {
          if (Array.isArray(node)) return node.forEach(visit);
          if (!node || typeof node !== 'object') return;
          nodes.push({ file: file.slice(ROOT.length), node });
          Object.values(node).forEach(visit);
        };
        visit(data);
      } catch (error) {
        parseErrors.push(`${file.slice(ROOT.length)}: ${error.message}`);
      }
    }
  }

  const typesOf = node => [].concat(node['@type'] || []);

  it('every JSON-LD block on every page parses', () => {
    expect(parseErrors).toEqual([]);
  });

  it('every Product node carries offers, review or aggregateRating', () => {
    // Google's requirement. Without one of the three the item is invalid and earns no
    // rich result. Unpriced items must be SoftwareApplication instead.
    const invalid = nodes
      .filter(({ node }) => typesOf(node).includes('Product'))
      .filter(({ node }) => !['offers', 'review', 'aggregateRating'].some(k => k in node))
      .map(({ file, node }) => `${file}: ${node.name || '(unnamed)'}`);
    expect(invalid).toEqual([]);
  });

  it('the Starter Pack offer price matches server/checkout.js', async () => {
    // The one place a price appears in markup. Generated from the same constant the
    // server charges from, so the two cannot drift.
    const { CATALOG } = await import('../server/checkout.js');
    const expected = (CATALOG.pack.amount / 100).toFixed(2);
    const bundle = nodes.find(({ node }) => node['@id'] === 'https://felican.ai/starter-pack/#bundle');
    expect(bundle).toBeTruthy();
    expect(bundle.node.offers.price).toBe(expected);
    expect(bundle.node.offers.priceCurrency).toBe('USD');
  });

  it('every Offer price in markup comes from server/checkout.js', async () => {
    // Product pages and the Starter Pack are the only places an Offer appears, and
    // both figures are generated from CATALOG so markup and charge cannot diverge.
    const { CATALOG } = await import('../server/checkout.js');
    const product = (CATALOG['private-ai'].amount / 100).toFixed(2);
    const pack = (CATALOG.pack.amount / 100).toFixed(2);
    const allowed = new Set([product, pack]);

    const offers = nodes.filter(({ node }) => 'price' in node);
    expect(offers.length).toBeGreaterThan(0);
    const wrong = offers
      .filter(({ node }) => !allowed.has(String(node.price)))
      .map(({ file, node }) => `${file}: ${node.price}`);
    expect(wrong).toEqual([]);

    const outside = offers
      .filter(({ file }) => !file.includes('/starter-pack/') && !file.includes('/products/'))
      .map(({ file }) => file);
    expect([...new Set(outside)]).toEqual([]);
  });
});
