#!/usr/bin/env node
// Adds intrinsic width/height, loading and decoding attributes to <img> tags that
// lack them, across the hand-written pages.
//
// Why: an <img> with no width/height gives the browser nothing to reserve space with,
// which is the standard cause of Cumulative Layout Shift — one of the three Core Web
// Vitals, measured at the 75th percentile of real visits. /products/ also loaded
// nineteen product screenshots with no lazy loading at all.
//
// Dimensions are read from the actual PNG/JPEG headers, so the aspect ratio the
// browser reserves matches the file. Images whose src is a {{ template }} expression
// are skipped: the file is only known at runtime. Those carry explicit CSS
// aspect-ratio boxes in the page styles instead.
//
// Run with `npm run fix:images`. Idempotent.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { globSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

function pngSize(buf) {
  if (buf.length < 24 || buf.readUInt32BE(0) !== 0x89504e47) return null;
  return { w: buf.readUInt32BE(16), h: buf.readUInt32BE(20) };
}

function jpgSize(buf) {
  let i = 2;
  while (i < buf.length - 9) {
    if (buf[i] !== 0xff) { i++; continue; }
    const marker = buf[i + 1];
    if ([0xc0, 0xc1, 0xc2, 0xc3, 0xc5, 0xc6, 0xc7, 0xc9, 0xca, 0xcb, 0xcd, 0xce, 0xcf].includes(marker)) {
      return { h: buf.readUInt16BE(i + 5), w: buf.readUInt16BE(i + 7) };
    }
    if (marker === 0xd8 || marker === 0xd9 || (marker >= 0xd0 && marker <= 0xd7)) { i += 2; continue; }
    i += 2 + buf.readUInt16BE(i + 2);
  }
  return null;
}

const cache = new Map();
function dimensions(src) {
  const clean = src.split('?')[0].split('#')[0];
  if (cache.has(clean)) return cache.get(clean);
  const file = join(ROOT, 'public', clean.replace(/^\//, ''));
  let out = null;
  if (existsSync(file)) {
    const buf = readFileSync(file);
    out = /\.png$/i.test(clean) ? pngSize(buf) : /\.jpe?g$/i.test(clean) ? jpgSize(buf) : null;
  }
  cache.set(clean, out);
  return out;
}

const files = [
  'index.html',
  ...globSync('public/**/index.html', { cwd: ROOT }),
  ...globSync('public/*.dc.html', { cwd: ROOT }),
].filter(f => !readFileSync(join(ROOT, f), 'utf8').startsWith('<!-- Generated by scripts/build-content.mjs'));

let touched = 0;
let tags = 0;
let skipped = 0;

for (const rel of files) {
  const file = join(ROOT, rel);
  const html = readFileSync(file, 'utf8');
  let changes = 0;

  const next = html.replace(/<img\b[^>]*>/gi, tag => {
    const srcMatch = tag.match(/\bsrc="([^"]+)"/i);
    const hasW = /\bwidth=/i.test(tag);
    const hasH = /\bheight=/i.test(tag);
    const hasLoading = /\bloading=/i.test(tag);
    const hasDecoding = /\bdecoding=/i.test(tag);

    // A templated src ({{ ... }}) or a data-product-image placeholder resolves at
    // runtime, so there is no file to measure. Leave those alone.
    const templated = !srcMatch || srcMatch[1].includes('{{');

    const additions = [];
    if (!templated && (!hasW || !hasH)) {
      const size = dimensions(srcMatch[1]);
      if (size) {
        if (!hasW) additions.push(`width="${size.w}"`);
        if (!hasH) additions.push(`height="${size.h}"`);
      } else {
        skipped++;
      }
    }
    // The logo in the sticky header is above the fold on every page and must not be
    // lazy-loaded; everything else in these files is below it.
    const isHeaderLogo = /logo-mark\.png/.test(tag) && /width="2[68]"/.test(tag + additions.join(' '));
    if (!hasLoading && !isHeaderLogo) additions.push('loading="lazy"');
    if (!hasDecoding) additions.push('decoding="async"');

    if (!additions.length) return tag;
    changes++;
    tags++;
    return tag.replace(/\s*\/?>$/, ` ${additions.join(' ')}>`);
  });

  if (changes) { writeFileSync(file, next); touched++; }
}

console.log(`Images: ${tags} tag(s) updated across ${touched} file(s).`);
if (skipped) console.log(`  ${skipped} tag(s) had a src with no measurable file — left unchanged.`);
