#!/usr/bin/env node
// Replaces the hand-copied Organization/WebSite JSON-LD in every hand-written page
// with the single generated graph from content/site.js.
//
// Why: the old graph was copy-pasted into all thirteen pages, had no `sameAs` (so
// nothing disambiguated "Felican AI" from Felician University, felican.net and
// felican.in), no address, and no Person node for the founder. With ~85 pages it has
// to come from one place.
//
// Strictly idempotent: it removes EVERY block whose graph contains an Organization
// node, then inserts exactly one. An earlier version matched on a literal
// `"@type":"Organization"` prefix, missed a variant form, and appended a second block
// instead of replacing the first — so the removal pass here is deliberately broad.
//
// Run with `npm run sync:schema`.

import { readFileSync, writeFileSync } from 'node:fs';
import { globSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { organizationNode, founderNode, websiteNode } from './seo/render.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const graph = { '@context': 'https://schema.org', '@graph': [organizationNode(), founderNode(), websiteNode()] };
const block = `<script type="application/ld+json">${JSON.stringify(graph).replace(/</g, '\\u003c')}</script>`;

const GENERATED = '<!-- Generated by scripts/build-content.mjs';

// Hand-written pages only. Generated pages render the graph from source every build.
const targets = [
  'index.html',
  ...globSync('public/**/index.html', { cwd: ROOT }),
].filter(f => !readFileSync(join(ROOT, f), 'utf8').startsWith(GENERATED));

// True when this JSON-LD payload is an Organization-identity graph (as opposed to a
// page's own Product, ItemList or Article markup, which must be left alone).
function isIdentityGraph(payload) {
  try {
    const data = JSON.parse(payload.replace(/\\u003c/g, '<'));
    const nodes = data['@graph'] || [data];
    const types = nodes.flatMap(n => [].concat(n['@type'] || []));
    // An identity graph's defining feature: it carries Organization and does NOT
    // carry a page-specific type that would be lost by replacing it.
    return types.includes('Organization')
      && !types.some(t => ['Product', 'ItemList', 'Article', 'Book', 'Service', 'SoftwareApplication'].includes(t));
  } catch {
    return false;
  }
}

let replaced = 0;
let added = 0;
let removedDuplicates = 0;

for (const rel of targets) {
  const file = join(ROOT, rel);
  const original = readFileSync(file, 'utf8');
  let html = original;

  // Remove every identity block, then insert exactly one. Doing it in two phases
  // avoids the trap that chained replace() calls fall into when the old and new
  // blocks are byte-identical: the second replace then deletes what the first
  // inserted, and the page ends up with no graph at all.
  const blocks = [...html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)]
    .filter(m => isIdentityGraph(m[1]))
    .map(m => m[0]);

  const unique = [...new Set(blocks)];
  for (const found of unique) html = html.split(found).join('');
  html = html.replace(/\n{3,}/g, '\n\n');
  // Collapse whatever whitespace the removal left immediately before </head>, so the
  // insertion below lands in the same place every run and the output is stable.
  html = html.replace(/\s*<\/head>/, '\n</head>');

  if (blocks.length) {
    replaced++;
    removedDuplicates += blocks.length - 1;
  } else {
    added++;
  }

  if (html.includes('</head>')) {
    html = html.replace('</head>', `${block}\n</head>`);
  } else {
    console.warn(`  ! ${rel} has no </head> — skipped`);
    continue;
  }

  if (html !== original) writeFileSync(file, html);
}

console.log(`Organization graph: ${replaced} replaced, ${added} added, ${removedDuplicates} duplicate block(s) removed.`);
